[[linter]]
code = "UFMT"
include_patterns = [
    "efa/**/*.py",
    "efa/**/*.pyi",
    "ibverbs/**/*.py",
    "ibverbs/**/*.pyi",
    "nvmeof/**/*.py",
    "nvmeof/**/*.pyi",
    "benchmarks/**/*.py",
    "docs/**/*.py",
    "experiments/**/*.py",
    "tools/**/*.py",
]
exclude_patterns = []
init_command = [
    "python3",
    "tools/linter/adapters/pip_init.py",
    "--dry-run={{DRYRUN}}",
    "black==26.5.1",
    "ufmt==2.8.0",
    "usort==1.1.3",
]
command = [
    "python3",
    "tools/linter/adapters/ufmt_linter.py",
    "--",
    "@{{PATHSFILE}}",
]
is_formatter = true

[[linter]]
code = "RUFF"
include_patterns = [
    "efa/**/*.py",
    "efa/**/*.pyi",
    "ibverbs/**/*.py",
    "ibverbs/**/*.pyi",
    "nvmeof/**/*.py",
    "nvmeof/**/*.pyi",
    "benchmarks/**/*.py",
    "docs/**/*.py",
    "experiments/**/*.py",
    "tools/**/*.py",
]
exclude_patterns = []
init_command = [
    "python3",
    "tools/linter/adapters/pip_init.py",
    "--dry-run={{DRYRUN}}",
    "ruff==0.15.22",
]
command = [
    "python3",
    "tools/linter/adapters/ruff_linter.py",
    "--",
    "@{{PATHSFILE}}",
]
is_formatter = false

[[linter]]
code = "PYRE"
include_patterns = [
    "efa/src/efa/**/*.py",
    "efa/src/efa/**/*.pyi",
    "ibverbs/src/ibverbs/**/*.py",
    "ibverbs/src/ibverbs/**/*.pyi",
    "experiments/**/*.py",
    "nvmeof/src/nvmeof/**/*.py",
    "nvmeof/src/nvmeof/**/*.pyi",
]
exclude_patterns = []
init_command = [
    "python3",
    "tools/linter/adapters/pip_init.py",
    "--dry-run={{DRYRUN}}",
    "pyre-check-nightly==0.0.101757589089",
]
command = [
    "python3",
    "tools/linter/adapters/pyre_linter.py",
    "--",
    "@{{PATHSFILE}}",
]
is_formatter = false
